### ISSUE TITLE
El link para descargar los datos scrapeados hasta ahora está roto

### ISSUE THREAD

**Issue by vasquez343** [builker-col/bogota-apartments#45]
No puedo descargar los datos scrapeados en 2024. Solo lo del 2023.

**Comment by Erik172** [comment]
Hola @vasquez343, lamento lo sucedido. Los enlaces ya están disponibles nuevamente, y puedes descargar tanto los archivos raw como los procesados desde el último release en este enlace: [https://github.com/builker-col/bogota-apartments/releases/tag/v2.0.0-august.2-2024](https://github.com/builker-col/bogota-apartments/releases/tag/v2.0.0-august.2-2024).

Debido a errores en la migración, no contamos con los datos desde enero 😔, pero tenemos la información desde julio hasta agosto. Estamos trabajando para agregar los datos de septiembre, de modo que haya más fuentes disponibles y sean más útiles.

![apartments_by_month](https://github.com/user-attachments/assets/1454c016-3c80-4c21-bca9-29ea7a292dd1)

![output](https://github.com/user-attachments/assets/2271524f-1a27-4446-ba11-483064a9e9ba)
